name: update epg
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4
        
      - name: checkout fraudiay79/epg-grab repo
        uses: actions/checkout@v4
        with:
         repository: fraudiay79/epg-grab
         path: fraudiay79-epg-grab

      - name: npm grab epg
        run: |
          npm install
          npm run grab --- --channels=../epg/channels/channels.xml --gzip --output=../epg/epg-channels.xml.gz --days=2 --maxConnections=20 --timeout=90000

      - name: setup git config
        run: |
          git config user.name "🧟 Brainz"
          git config user.email "<>"

      - name: commit
        run: |
          git add -f epg/epg-channels.xml.gz
          git commit -m "updated epg"
          git push
