name: update epg
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4
        
      - name: checkout fraudiay79/epg-grab repo
        uses: actions/checkout@v4
        with:
         repository: fraudiay79/epg-grab
         path: fraudiay79-epg-grab

      - name: update EPG
        run: sh epg/epg_main.sh

      - name: setup git config
        run: |
          git config user.name "🧟 Brainz"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd epg && git add .
          git commit -m "updated epg"
          git push
