name: Update EPG
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v6
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v6
        with:
         repository: iptv-org/epg
         path: iptv-org-epg

      - name: update EPG
        run: sh epg/epg_main.sh

      - name: setup git config
        run: |
          git config user.name "🧟 Brainz"
          git config user.email "<>"

      - name: commit
        run: |
          git add -f epg/epg-channels.xml.gz
          git commit -m "Update EPG"
          git push -f origin main
