name: Update Giniko Streams

on:
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-streams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm python-slugify
        
    - name: Run Giniko script
      run: |
        cd ./platforms/
        python giniko.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email ""
          git config --local user.name "Stream Ninja 🥷🏽"
          git add -A
          git commit -m "updated streams"
          git push
