name: Fetch M3U8 via Proxy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create directories
      run: |
        mkdir -p platforms/links/fi
      
    - name: Fetch M3U8 through Proxy
      run: |
        PROXY_BASE="https://bbc.mesutgokhan10.workers.dev"
        
        echo "=== Step 1: Get M3U8 URL from API ==="
        JSON_RESPONSE=$(curl -s "$PROXY_BASE/?mediaId=2584964")
        M3U8_URL=$(echo "$JSON_RESPONSE" | jq -r '.clip.playback.media.streamUrls.webHls.url')
        
        if [ -n "$M3U8_URL" ] && [ "$M3U8_URL" != "null" ]; then
            echo "✅ M3U8 URL: $M3U8_URL"
            
            echo "=== Step 2: Fetch M3U8 content through proxy ==="
            # URL encode the M3U8 URL for the proxy
            ENCODED_URL=$(echo -n "$M3U8_URL" | sed 's/ /%20/g')
            
            # Fetch through proxy
            curl -s "$PROXY_BASE/?getM3U8=$ENCODED_URL" -o platforms/links/fi/jim.m3u8
            
            echo "=== Step 3: Validate M3U8 ==="
            if [ -s "platforms/links/fi/jim.m3u8" ]; then
                LINES=$(wc -l < platforms/links/fi/jim.m3u8)
                BYTES=$(wc -c < platforms/links/fi/jim.m3u8)
                echo "File stats: $LINES lines, $BYTES bytes"
                
                if head -1 platforms/links/fi/jim.m3u8 | grep -q "EXTM3U"; then
                    echo "✅ Valid M3U8 file"
                    echo "First 3 lines:"
                    head -3 platforms/links/fi/jim.m3u8
                else
                    echo "❌ Invalid M3U8 format"
                    echo "First line: $(head -1 platforms/links/fi/jim.m3u8)"
                    exit 1
                fi
            else
                echo "❌ File is empty"
                exit 1
            fi
            
        else
            echo "❌ Could not extract M3U8 URL"
            exit 1
        fi
        
    - name: Commit and push
      run: |
        if [ -s platforms/links/fi/jim.m3u8 ]; then
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add platforms/links/fi/jim.m3u8
          git diff --staged --quiet || git commit -m "Update Jim M3U8 - $(date +'%Y-%m-%d %H:%M UTC')"
          git push
          echo "✅ Successfully updated Jim M3U8"
        else
          echo "❌ File is empty, cannot commit"
          exit 1
        fi
