name: Fetch M3U8 via Proxy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Fetch via Proxy
      run: |
        PROXY_URL="https://bbc.mesutgokhan10.workers.dev/?mediaId=2584964"
        OUTPUT_DIR="platforms/links/fi"
        OUTPUT_FILE="$OUTPUT_DIR/jim.m3u8"
        
        # Create directory if it doesn't exist
        mkdir -p "$OUTPUT_DIR"
        
        echo "Fetching JSON from proxy..."
        JSON_RESPONSE=$(curl -s "$PROXY_URL")
        
        # Extract the m3u8 URL using the correct path
        M3U8_URL=$(echo "$JSON_RESPONSE" | jq -r '.clip.playback.media.streamUrls.webHls.url')
        
        if [ -n "$M3U8_URL" ] && [ "$M3U8_URL" != "null" ]; then
            echo "✅ Extracted URL: $M3U8_URL"
            
            # Download m3u8 content
            echo "Downloading m3u8 content..."
            curl -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
                 -H "Referer: https://www.nelonenmedia.fi/" \
                 "$M3U8_URL" | \
            awk -v base="${M3U8_URL%/*}/" '
            /^[^#].*\.m3u8/ {
                if ($0 ~ /^https?:\/\//) print $0
                else print base $0
                next
            }
            { print }' > "$OUTPUT_FILE"
            
            echo "✅ M3U8 file created successfully at: $OUTPUT_FILE"
            echo "First few lines:"
            head -5 "$OUTPUT_FILE"
            
        else
            echo "❌ Failed to extract URL"
            exit 1
        fi
        
    - name: Commit and push
      run: |
        OUTPUT_FILE="platforms/links/fi/jim.m3u8"
        if [ -s "$OUTPUT_FILE" ]; then
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add "$OUTPUT_FILE"
          git diff --staged --quiet || git commit -m "Update FI Jim m3u8 - $(date +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "❌ $OUTPUT_FILE is empty, skipping commit"
          exit 1
        fi
