name: grabbing streams

on:
  schedule:
    - cron: '0 */4 * * *'
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
            python3 twitch.py hadramout1 > ../../streams/hadhramaut.m3u8
            python3 twitch.py libyaonetv > ../../streams/libyaonetv.m3u8
            python3 twitch.py tv47kenya > ../../streams/tv47kenya.m3u8
            python3 twitch.py alrassoulchannel > ../../streams/alrassoul.m3u8
            python3 twitch.py ntvickakanj > ../../streams/ntvickakanj.m3u8
            python3 dailymotion.py x97hh7o > ../../streams/alaan.m3u8
            python3 dailymotion.py x8e61qj > ../../streams/dvbmm.m3u8
            python3 twitch.py elnueve_ok > ../../streams/elnueve.m3u8
            python3 twitch.py mrtvnewslive > ../../streams/mrtvnews.m3u8
            python3 twitch.py livestreamingmrtv > ../../streams/mrtv.m3u8
            python3 twitch.py mitvlivestream > ../../streams/mitv.m3u8
            python3 twitch.py paraguaytvhd > ../../streams/paraguaytv.m3u8
            python3 twitch.py abcnewsal > ../../streams/abcnewsal.m3u8
            python3 dailymotion.py x7x4dgx > ../../streams/willax.m3u8
            python3 dailymotion.py x84nwne > ../../streams/niletv.m3u8
            python3 dailymotion.py x8lr1r8 > ../../streams/nileint.m3u8
            python3 dailymotion.py x8n6e4h > ../../streams/maspero.m3u8
            python3 dailymotion.py x856hbh > ../../streams/ertu1.m3u8
            python3 dailymotion.py x8n6dm7 > ../../streams/ertu2.m3u8
            python3 dailymotion.py x84nun4 > ../../streams/masriya.m3u8
            python3 dailymotion.py x8n6e3a > ../../streams/niledrama.m3u8
            python3 dailymotion.py x7va0xb > ../../streams/nessma.m3u8
            python3 dailymotion.py x7ooijz > ../../streams/elhiwartn.m3u8
            python3 dailymotion.py x84eirw > ../../streams/atb.m3u8
            python3 dailymotion.py x5gv5rr > ../../streams/c8.m3u8
            python3 twitch.py elbaladtv > ../../streams/elbaladtv.m3u8
            
            
      - name: git add
        run: |
          git add -A
          ls -la 
          git commit -m "initial commit"
          git push origin main
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push -f origin master
