name: Fetch TMDb Data

on:
  
  workflow_dispatch: # Allows manual execution
  push:
    paths:
      - 'meta/tmdb.py' # Runs when the script is updated

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run TMDb Script for TV Shows & Movies
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: python meta/tmdb.py

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Push to Different Repository
      env:
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        TARGET_BRANCH: "main"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote add target https://github.com/${TARGET_REPO}.git
        git add meta/shows/*.json meta/movies/movies.json
        git commit -m "Update TMDb data for TV shows and movies"
        git push target HEAD:$TARGET_BRANCH
