name: Fetch TMDb Data

on:
  
  workflow_dispatch: # Allows manual execution
  push:
    paths:
      - 'meta/tmdb.py' # Runs when the script is updated

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run TMDb Script
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: python meta/tmdb.py

    - name: Commit & Push Data
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add meta/shows/supernatural.json
        git commit -m "Update Supernatural data from TMDb"
        git push
      continue-on-error: true
