name: tvm action

on:
  schedule:
    - cron: '0 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      - name: updating tvm
        run: |
            pwd
            cd ./core/platforms/
            python3 tvm.py > ../../streams/tvm.m3u8
            python3 tvmnews.py > ../../streams/tvmnews.m3u8
            python3 tvmsport.py > ../../streams/tvmsport.m3u8
            
      - name: git add
        run: |
          git add -A
          ls -la  
          git commit -m "initial commit"
          git push origin main
          
      - name: commit & push
        run: |
          git commit -m "tvm updated"
          git push -f origin master
