name: YouTube HLS Downloader with yt-dlp

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  download_hls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Run Script
        run: |
          cd ./platforms/
          python yt_m3u8_downloader.py

      - name: m3u8 create and move folder
        run: |
          mkdir -p m3u8
          mv *.m3u8 m3u8/ || echo "No files to move."

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u8/*.m3u8 || true
          git diff --cached --quiet || (git commit -m "Update m3u8 files [skip ci]" && git push)

      - name: Artifacts olarak ekle (isteğe bağlı)
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-dosyaları
          path: m3u8/*.m3u8
